const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Browser.Exps.ExecJS,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{М1Фон: 0},
	{М1КНормСтрем: 0},
	{М1КПожелания: 0},
	{М1ТКНормилистрем: 0},
	{М1ТКПожелания: 0},
	{Тач: 0},
	{Текст: 0},
	{М1КПодушам: 0},
	{М1ТКподушам: 0},
	{М1КИдеисвиданий: 0},
	{М1ТКИдеисвиданий: 0},
	{М1ДО: 0},
	{М1ТекстСвидания: 0},
	{М1КЗдорово: 0},
	{М1ТКЗдорово: 0},
	{М17фон: 0},
	{М17до: 0},
	{М17ТекстЯнварь: 0},
	{М17Кздорово: 0},
	{М17ткмывделе: 0},
	{М18фон: 0},
	{М18ДО: 0},
	{М18Кмывделе: 0},
	{М18ткмывделе: 0},
	{М18Текстсвиданияфевраль: 0},
	{М19фон: 0},
	{М19до: 0},
	{М19кмывделе: 0},
	{М19ткмывделе: 0},
	{М19текстмарт: 0},
	{М20фон: 0},
	{М20до: 0},
	{М20кмывделе: 0},
	{М20темывделе: 0},
	{М20текстапрель: 0},
	{М21фон: 0},
	{М21ДО: 0},
	{М21кмывделе: 0},
	{М21ткмывделе: 0},
	{М21текстмай: 0},
	{М22фон: 0},
	{М22до: 0},
	{М22кмывделе: 0},
	{М22ткмывделе: 0},
	{М22текстиюнь: 0},
	{М23фон: 0},
	{М23до: 0},
	{М23кмыаделе: 0},
	{М23ткмывделе: 0},
	{М23текстИюль: 0},
	{М24фон: 0},
	{М24до: 0},
	{М24кмывделе: 0},
	{М24ткмывделе: 0},
	{М24текставгуст: 0},
	{М25фон: 0},
	{М25до: 0},
	{М25кмывделе: 0},
	{М25ткмывделе: 0},
	{М25текстсентябрь: 0},
	{М26фон: 0},
	{м26до: 0},
	{м26кмывделе: 0},
	{м26ткмывделе: 0},
	{м26текстоктябрь: 0},
	{м27фон: 0},
	{м27до: 0},
	{м27кмывделе: 0},
	{м27ткмывделе: 0},
	{м27текстноябрь: 0},
	{М28фон: 0},
	{м28до: 0},
	{м28кмывделе: 0},
	{м28ткмывделе: 0},
	{М28текстдекабрь: 0},
	{Браузер: 0},
	{ЛокальноеХранилище: 0},
	{м1Год: 0},
	{м1Месяц: 0},
	{М1Число: 0}
];

self.InstanceType = {
	М1Фон: class extends self.ISpriteInstance {},
	М1КНормСтрем: class extends self.ISpriteInstance {},
	М1КПожелания: class extends self.ISpriteInstance {},
	М1ТКНормилистрем: class extends self.ITextInstance {},
	М1ТКПожелания: class extends self.ITextInstance {},
	Тач: class extends self.IInstance {},
	Текст: class extends self.ITextInstance {},
	М1КПодушам: class extends self.ISpriteInstance {},
	М1ТКподушам: class extends self.ITextInstance {},
	М1КИдеисвиданий: class extends self.ISpriteInstance {},
	М1ТКИдеисвиданий: class extends self.ITextInstance {},
	М1ДО: class extends self.ISpriteInstance {},
	М1ТекстСвидания: class extends self.ITextInstance {},
	М1КЗдорово: class extends self.ISpriteInstance {},
	М1ТКЗдорово: class extends self.ITextInstance {},
	М17фон: class extends self.ISpriteInstance {},
	М17до: class extends self.ISpriteInstance {},
	М17ТекстЯнварь: class extends self.ITextInstance {},
	М17Кздорово: class extends self.ISpriteInstance {},
	М17ткмывделе: class extends self.ITextInstance {},
	М18фон: class extends self.ISpriteInstance {},
	М18ДО: class extends self.ISpriteInstance {},
	М18Кмывделе: class extends self.ISpriteInstance {},
	М18ткмывделе: class extends self.ITextInstance {},
	М18Текстсвиданияфевраль: class extends self.ITextInstance {},
	М19фон: class extends self.ISpriteInstance {},
	М19до: class extends self.ISpriteInstance {},
	М19кмывделе: class extends self.ISpriteInstance {},
	М19ткмывделе: class extends self.ITextInstance {},
	М19текстмарт: class extends self.ITextInstance {},
	М20фон: class extends self.ISpriteInstance {},
	М20до: class extends self.ISpriteInstance {},
	М20кмывделе: class extends self.ISpriteInstance {},
	М20темывделе: class extends self.ITextInstance {},
	М20текстапрель: class extends self.ITextInstance {},
	М21фон: class extends self.ISpriteInstance {},
	М21ДО: class extends self.ISpriteInstance {},
	М21кмывделе: class extends self.ISpriteInstance {},
	М21ткмывделе: class extends self.ITextInstance {},
	М21текстмай: class extends self.ITextInstance {},
	М22фон: class extends self.ISpriteInstance {},
	М22до: class extends self.ISpriteInstance {},
	М22кмывделе: class extends self.ISpriteInstance {},
	М22ткмывделе: class extends self.ITextInstance {},
	М22текстиюнь: class extends self.ITextInstance {},
	М23фон: class extends self.ISpriteInstance {},
	М23до: class extends self.ISpriteInstance {},
	М23кмыаделе: class extends self.ISpriteInstance {},
	М23ткмывделе: class extends self.ITextInstance {},
	М23текстИюль: class extends self.ITextInstance {},
	М24фон: class extends self.ISpriteInstance {},
	М24до: class extends self.ISpriteInstance {},
	М24кмывделе: class extends self.ISpriteInstance {},
	М24ткмывделе: class extends self.ITextInstance {},
	М24текставгуст: class extends self.ITextInstance {},
	М25фон: class extends self.ISpriteInstance {},
	М25до: class extends self.ISpriteInstance {},
	М25кмывделе: class extends self.ISpriteInstance {},
	М25ткмывделе: class extends self.ITextInstance {},
	М25текстсентябрь: class extends self.ITextInstance {},
	М26фон: class extends self.ISpriteInstance {},
	м26до: class extends self.ISpriteInstance {},
	м26кмывделе: class extends self.ISpriteInstance {},
	м26ткмывделе: class extends self.ITextInstance {},
	м26текстоктябрь: class extends self.ITextInstance {},
	м27фон: class extends self.ISpriteInstance {},
	м27до: class extends self.ISpriteInstance {},
	м27кмывделе: class extends self.ISpriteInstance {},
	м27ткмывделе: class extends self.ITextInstance {},
	м27текстноябрь: class extends self.ITextInstance {},
	М28фон: class extends self.ISpriteInstance {},
	м28до: class extends self.ISpriteInstance {},
	м28кмывделе: class extends self.ISpriteInstance {},
	м28ткмывделе: class extends self.ITextInstance {},
	М28текстдекабрь: class extends self.ITextInstance {},
	Браузер: class extends self.IInstance {},
	ЛокальноеХранилище: class extends self.IInstance {}
}